# application.yml —— 本地默认用 MySQL；线上用环境变量覆盖
server:
  port: ${PORT:8080}   # Render/其他平台会注入 PORT，本地默认 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 兼容云平台提供的 MYSQL* 环境变量；本地默认指向 localhost
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:bbs}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:1234}

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

# 自定义应用配置
app:
  jwt:
    # 线上用环境变量覆盖：JWT_SECRET / JWT_EXPIRE_MINUTES
    secret: ${JWT_SECRET:CHANGE_ME_TO_64+_RANDOM_CHARS_____________________________________}
    expire-minutes: ${JWT_EXPIRE_MINUTES:120}
  # 允许的前端域名（逗号分隔），被 CorsConfig 读取
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}

---
# ===== Render 专用分节：启用 render profile 时，切换到 H2 文件库 =====
spring:
  config:
    activate:
      on-profile: render
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/app;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_UPPER=false
    username: sa
    password:
  # 如启用了 Flyway 且没有 H2 脚本，先关闭，避免启动报 "no such table"
  flyway:
    enabled: false
